### ISSUE TITLE
Support GH organization folders

### ISSUE THREAD

**Issue by bluesliverx** [jenkinsci/github-pr-comment-build-plugin#1]
From Jesse Glick: `BranchProperty will not suffice for a GH org folder I think. You would need an AbstractFolderProperty<OrganizationFolder>.`

**Comment by bluesliverx** [comment]
Apparently this functionality was rolled into the github branch source plugin, so just make sure we support it there.

**Comment by samdmarshall** [comment]
Hey, what is the status of this? Is there any way that I could register a rebuild to happen when a comment with specific text contents (as this plugin is described) is posted to a PR when using the Github branch source plugin?

**Comment by bluesliverx** [comment]
Yes, the functionality is working - I just haven't verified support with GitHub organization folders yet.

**Comment by samdmarshall** [comment]
cool, could you point me to an example of using this with a jenkinsfile or pipeline script? we haven't been able to figure out how to get called from there.

**Comment by ajzaff** [comment]
In a GHO folder, the branch configuration is read-only, so you'll need folder-level config.

**Comment by gimler** [comment]
any news?

**Comment by bluesliverx** [comment]
@samdmarshall please see #4 and #5 for more info on calling it from Jenkinsfile or pipeline scripts, this is not the way the plugin is intended to be used. It must be configured on the multibranch job.

@gimler as for GH organization folders, I haven't looked into them at all since we don't use them at all currently.  That may change in the future, but it likely will not be soon. I'm very open to PRs to add this functionality if you figure out how to do this.  Sorry I don't have a better answer, but since this is for work and I don't use this functionality in my home projects, I'm kind of limited to what I can do here.

**Comment by bluesliverx** [comment]
It looks like this is actually only possible (without a lot of work on this plugin) through the pipeline script as long as you have the "Pipeline GitHub" plugin installed:

https://github.com/jenkinsci/pipeline-github-plugin#issuecommenttrigger

If you add that trigger to your pipeline script, it should trigger correctly, according to the docs. I'm closing this ticket since according to [this Jenkins ticket|https://issues.jenkins-ci.org/browse/JENKINS-33900?focusedCommentId=326187&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-326187], it is by design that branch properties cannot be configured on github orgs. It should all be done through pipeline scripts for them.
