### ISSUE TITLE
Feature: Build on PR reviews

### ISSUE THREAD

**Issue by mloo-sp** [jenkinsci/github-pr-comment-build-plugin#10]
Would you be open to adding a feature to initiate a build on a pull request review event?  

Also, are you accepting pull requests?

**Comment by bluesliverx** [comment]
I am very open to this, I believe the latest version of the GitHub API plugin and the enterprise GitHub version we were on together when I wrote this didn't support pull request review events as of yet, so I would love to see them added.

Pull requests are very welcome, I would love it if you could add this functionality as I probably won't pick it up soon.

**Comment by bluesliverx** [comment]
I have released version 2.1, which should have these changes, let me know if something doesn't look right, I can't test it out myself until next week most likely.
