### ISSUE TITLE
PR COMMENT is not triggering jenkins build

### ISSUE THREAD

**Issue by saheerb** [jenkinsci/github-pr-comment-build-plugin#15]
A little bit of background:

In my current project, the entire pipeline job is very time-consuming. it has Build + test. So, we decided to run the Build + Test only on specific branches. (This is achieved by "when" syntax). Also, we want to build the pipeline forcefully for a Pull request with a comment/action in the pull request. So, we ended up trying this plugin.

I have tried a few options but still not able to get the build to trigger with PR comment. 

This is my Jenkins configuration:

<img width="908" alt="Screenshot 2019-07-31 at 13 28 49" src="https://user-images.githubusercontent.com/31441397/62211841-7243f280-b397-11e9-905d-a7940441a496.png">

Does it look alright?

I have also set GitHub server in administration

![Screenshot 2019-07-31 at 13 33 36](https://user-images.githubusercontent.com/31441397/62212050-db2b6a80-b397-11e9-9f8c-fdd6e517192b.png)

**By basic questions:**

1. Will this plugin trigger build even though there is no change in the commit? In my case, I will need to run some stages default and some other stages if build is triggered by comment plugin?
2. How can I know if the build is triggered by comment plugin?
3. Does the config look alright? What am I missing?

**Comment by bluesliverx** [comment]
1) Yes, it triggers even with no changes to commits
2) There is a cause added to the build (retrieved through the rawBuild in pipeline scripts I believe) with this class: https://github.com/jenkinsci/github-pr-comment-build-plugin/blob/master/src/main/java/com/adobe/jenkins/github_pr_comment_build/GitHubPullRequestCommentCause.java. You would have to check for that to know if a comment triggered it.
3) The config looks ok. I would double check that the hooks are setup properly and send all events (not just push events) to the Jenkins server. I would also take a look at the Jenkins logs (from within the Manage Jenkins pages) and watch the events coming in to make sure they are being properly sent. I would guess that you either a) are only sending push events from github or b) have some other misconfiguration on the system. I believe at one point there were also two types of github server configuration depending on which plugins you have installed, you might try checking for another github server config section in the Manage -> Configure page.

**Comment by saheerb** [comment]
A quick question really, will this plugin work just with scheduled build. (As I cannot configure the webhook)

**Comment by bluesliverx** [comment]
No, to do it without webhooks/events it would have to track the current comments somewhere in a database/filesystem and then trigger the build if it changed. Webhooks are really the only way to get this to work right.

**Comment by saheerb** [comment]
Thanks @bluesliverx

**Comment by akanshaallyo** [comment]
Use Case :- 
I am trying to trigger my pipeline on an issue commit.

Github Webhook - 
<img width="716" alt="Screenshot 2020-09-25 at 1 43 24 PM" src="https://user-images.githubusercontent.com/49449369/94244018-e1828b80-ff35-11ea-94d6-b54ec4fec486.png">


Jenkins Multibranch Pipeline - 
<img width="954" alt="Screenshot 2020-09-25 at 1 45 26 PM" src="https://user-images.githubusercontent.com/49449369/94244004-dcbdd780-ff35-11ea-87fc-c93942667922.png">


Jenkins Shared Library-
`    triggers {
      issueCommentTrigger('deploy on dev')
}`

This prints `Build was not started by a trigger` - 
`            if (triggerCause) {
              echo("Build was started by ${triggerCause.userLogin}, who wrote: " +
              "\"${triggerCause.comment}\", which matches the " +
              "\"${triggerCause.triggerPattern}\" trigger pattern.")
          } else {
              echo('Build was not started by a trigger')
            }`

It is triggering on every Issue comment rather than searching for `deploy on dev`. Have tried multiple of things not sure what is wrong

**Comment by bluesliverx** [comment]
@akanshaallyo This is a separate issue, but it looks like you already created a separate one.

**Comment by akanshaallyo** [comment]
@bluesliverx Yes I did --> https://github.com/jenkinsci/github-pr-comment-build-plugin/issues/24
