### ISSUE TITLE
PR Comment doesn't trigger a new build when not using webhooks

### ISSUE THREAD

**Issue by MarianMacik** [jenkinsci/github-pr-comment-build-plugin#21]
Hi guys,

short question, does this plugin also work without webhooks configured? We use GitHub Multibranch pipeline job which periodically checks the repository, see here:

![obrázok](https://user-images.githubusercontent.com/6797884/83668002-97b11680-a5cf-11ea-9755-45e0a008fe0e.png)

And we have the plugin configured like this:
![obrázok](https://user-images.githubusercontent.com/6797884/83668263-f5456300-a5cf-11ea-940a-7733d345f4c2.png)

But issuing a PR comment `jenkins retest this` doesn't trigger the build.

The version of Github Branch Source Plugin used is 2.5.4 and PR Comment Build Plugin is 2.1.

I also noticed that in documentation you have this stated:

`Please ensure that you have a GitHub server properly connected via the Jenkins configuration, or else the plugin will not operate correctly.`

Not sure what you mean by that.

Any help apprecaited!

Thanks

**Comment by bluesliverx** [comment]
I would not think it would work without hooks to be honest, since that is how it gets events. Scanning the repo periodically does not retrieve events.

The GitHub server needs to be configured in the Jenkins global configuration, that's all it means.

**Comment by MarianMacik** [comment]
> The GitHub server needs to be configured in the Jenkins global configuration, that's all it means.
@bluesliverx Which global configuration of Jenkins regarding GitHub server do you mean? Because right now I have GitHub repo configured directly in the job.

And I can confirm it works with webhooks.

**Comment by bluesliverx** [comment]
Oh, interesting. I guess that's an outdated requirement then. You used to have to add the GitHub server to global config in Jenkins, there's an area for GitHub servers that you can configure.

**Comment by MarianMacik** [comment]
OK, closing this issue then :)
