### ISSUE TITLE
Jenkins Build triggering on every Issue Comment rather on specific regex

### ISSUE THREAD

**Issue by akanshaallyo** [jenkinsci/github-pr-comment-build-plugin#24]
Use Case :-
I am trying to trigger my pipeline on an issue comment with `deploy on dev` in body

Github Webhook -
<img width="716" alt="Screenshot 2020-09-25 at 1 43 24 PM" src="https://user-images.githubusercontent.com/49449369/94244469-8d2bdb80-ff36-11ea-9d5f-7424504adccb.png">

Jenkins MultiBranch Pipeline - 
![image](https://user-images.githubusercontent.com/49449369/94244565-b2204e80-ff36-11ea-98e1-8cc7460963ff.png)

Jenkins Shared Library-
`triggers { issueCommentTrigger('deploy on dev') }`

This prints Build was not started by a trigger -

`if (triggerCause) { echo("Build was started by ${triggerCause.userLogin}, who wrote: " + "\"${triggerCause.comment}\", which matches the " + "\"${triggerCause.triggerPattern}\" trigger pattern.") } else { echo('Build was not started by a trigger') }`

It is triggering on every Issue comment rather than searching for `deploy on dev`. Have tried multiple of things not sure what is wrong`

**Comment by akanshaallyo** [comment]
Any update on this?

**Comment by bluesliverx** [comment]
Honestly, no, my life is hectic right now with personal stuff and work, and I don't really have time to look into this. It's on my backlog, but it'll be awhile. Feel free to open PRs if you identify what the problem could be. We use this exclusively and it works great, so there may be some version incompatibilities or something.

**Comment by akanshaallyo** [comment]
@bluesliverx 
Current Jenkins version - 2.177
Will try turning up the logging level

**Comment by akanshaallyo** [comment]
@bluesliverx Resolved by upgrading the Jenkins version form 2.177 --> 2.260

**Comment by bluesliverx** [comment]
Great to hear! I'll make a note.

**Comment by lpgutierrez** [comment]
:technologist:
