### ISSUE TITLE
Question - Github App Authentication - Does it work?

### ISSUE THREAD

**Issue by jrowinski3d** [jenkinsci/github-pr-comment-build-plugin#26]
Hi there,

I am trying to get this plugin to work, I have jobs configured via the GitHubSCMSource in a declarative pipeline.

While testing, I have setup for it to take any comments to trigger the build via **.\***

As of right now, I cannot get this to work at all. I guess my main question is if this plugin supports GithubApp authentication?

**Comment by bluesliverx** [comment]
Looks like you already closed this, did you find an answer to your question?

**Comment by jrowinski3d** [comment]
My permissions weren't approved yet for comments, so I wasnt patient enough on my side
