### ISSUE TITLE
Job is triggered twice with this plugin

### ISSUE THREAD

**Issue by hodaz** [jenkinsci/github-pr-comment-build-plugin#27]
Hi.
I am trying to use this plugin, but it triggers the job twice.
I found that SCMSourceOwner has duplicated jobs like
**job/name_of_job** and **job/name_of_job/job/name_of_repository/**
Could you fix the duplication? or could you let me know the way to avoid this situation?

**Comment by bluesliverx** [comment]
The plugin really doesn't do anything with defining jobs at all, that sounds like you have misconfigured the branch source plugin and the jobs themselves. It may depend on your configuration of the job properties for which branches it pulls in.

**Comment by prabusarav** [comment]
@hodaz .. how did you resolved this issue, i am facing the same issue, it would help, if you could share the configuration.

**Comment by lprimak** [comment]
Duplicate of #32
