### ISSUE TITLE
Get comment content?

### ISSUE THREAD

**Issue by Bjorn576** [jenkinsci/github-pr-comment-build-plugin#3]
Is there currently a way to retrieve the content of the comment that started a Jenkins build? It would be useful to have in the case of performing different build steps based on the nature of the comment.

**Comment by bluesliverx** [comment]
Yes, but you'll have to query for the comment by the URL.  You would need to retrieve this cause and then look at the getter for the comment URL:
https://github.com/jenkinsci/github-pr-comment-build-plugin/blob/master/src/main/java/com/adobe/jenkins/github_pr_comment_build/GitHubPullRequestCommentCause.java

**Comment by Bjorn576** [comment]
Ah, gotcha. Thanks!
