### ISSUE TITLE
The plugin is not triggered with a multibranch pipeline

### ISSUE THREAD

**Issue by julianatienza** [jenkinsci/github-pr-comment-build-plugin#31]
### Version report

Jenkins and plugins versions report:

```
latest
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
N/A
```

### Reproduction steps

- Installed plugin and related stuff
- Created a multibranch pipeline with webhook.
- Used a CURL with a valid payload of a github event trigerred by a comment

### Results

Expected result:

Creates a new build in the specific job for the specific pull request
Actual result:

Only trigger the scan with no logs from the plugin.

What this piece of code means? Perhaps is discarded for this reason, but I don't know what SCMSourceOwner implies. 
    @Override
    protected boolean isApplicable(Item item) {
        if (item != null && item instanceof Job<?, ?>) {
            Job<?, ?> project = (Job<?, ?>) item;
            if (project.getParent() instanceof SCMSourceOwner) {
                SCMSourceOwner owner = (SCMSourceOwner) project.getParent();
                for (SCMSource source : owner.getSCMSources()) {
                    if (source instanceof GitHubSCMSource) {
                        return true;
                    }
                }
            }
        }
        return false;
    }

**Comment by bluesliverx** [comment]
@julianatienza, I believe your problem may be related to #17. Can you confirm if the automatically added webhook is missing the "issue_comment" selection?

**Comment by lprimak** [comment]
This is fixed with the latest versions if Jenkins, you can close this issue
