### ISSUE TITLE
This plugin triggers the build twice

### ISSUE THREAD

**Issue by prabusarav** [jenkinsci/github-pr-comment-build-plugin#32]
### Version report

Jenkins and plugins versions report:

```
Plugin version - 2.3
Jenkins version - 2.235.1
--


<br class="Apple-interchange-newline">
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Paste here
```

### Reproduction steps

- Step 1 - Enable pull request review webhook in github (as mentioned below)
![image](https://user-images.githubusercontent.com/88445734/128202201-4fdc4c0d-ecaa-4b11-a734-aec36e326321.png)

- Step 2 - Configure build on pull request review - as shown below
![image](https://user-images.githubusercontent.com/88445734/128202562-366cdbea-3caa-4122-8509-2cb4769a52f2.png)

### Results

Expected result:

it should trigger a build only once when the pr is approved.

Actual result:

its triggering the build twice everytime when the pr is approved.

**Comment by bluesliverx** [comment]
Do you have a hook configured twice? Maybe once on the repository and once in the organization? That could cause two events to be sent and for it to be triggered twice.

If that's not it, try recreating the project, I've noticed strange things with projects in the past (though not in quite awhile, and not with this plugin) for older projects.

**Comment by prabusarav** [comment]
> Do you have a hook configured twice? Maybe once on the repository and once in the organization? That could cause two events to be sent and for it to be triggered twice.
> 
> If that's not it, try recreating the project, I've noticed strange things with projects in the past (though not in quite awhile, and not with this plugin) for older projects.

**Comment by prabusarav** [comment]
@bluesliverx thanks for the response

**Comment by bluesliverx** [comment]
@prabusarav, it might be helpful to check the Jenkins log. Create a new Jenkins log recorder that watches "com.cloudbees.jenkins.GitHubWebHook" (and possibly "org.jenkinsci.plugins.github") at the ALL level, and then see what event shows up. That will definitely say whether you are getting the events twice from GitHub or if it is something in the plugin (though how it could come from the plugin I have no idea, the github integration there is extremely simple and straightfoward).

**Comment by Ashok82** [comment]
I am facing same issue, only one hook configured at org level - delivered message shows only one. any pointers .

**Comment by bluesliverx** [comment]
This may be expected, depending on how GitHub delivers the hooks. i.e. if someone comments at the same time they are approving, that could end with two hook payloads sent: once for the pull request approval and once for the comment that goes with the approval.

**Comment by lprimak** [comment]
Same issue. The webhook is only configure and confirmed delivered once and only once.
Only one comment, no approvals. In fact, approvals are not enabled.
There should be only one build triggered.
This happens intermittently.

**Comment by lprimak** [comment]
Thanks! 
FYI @cubastanley

**Comment by bluesliverx** [comment]
Released in https://github.com/jenkinsci/github-pr-comment-build-plugin/releases/tag/67.va90f5cae5912
