### ISSUE TITLE
not able to retrieve getCommentBody or getCommentURL from currentBuild.buildCauses

### ISSUE THREAD

**Issue by om3171991** [jenkinsci/github-pr-comment-build-plugin#33]
Hey Team,

We are trying to get github comment body to trigger different stages of pipeline using "when" expression and hence need commentbody to check which comment triggered this build ..like "testpr" to run tests, "deploypr" to do deployment, etc.

We have set up a multibranch pipeline and trigger build based on comments by developer.

Pipeline script:

pipeline {
    agent { label 'any' }
    stages {
        stage('Pre-build') {
            steps {
                script {
                    dir("${WORKSPACE}") {
                        script {
                            echo "${glance_tag}"
                            **echo "${currentBuild.buildCauses}" // [[_class:com.adobe.jenkins.github_pr_comment_build.GitHubPullRequestCommentCause, shortDescription:GitHub pull request comment]]**
                            def buildCauses = currentBuild.buildCauses
                            **echo "$buildCauses.getCommentBody()" // gives null**
                            **echo "$buildCauses.getCommentUrl()"    // gives null**
                            **echo "$buildCauses.shortDescription"     //  gives GitHub pull request comment**
                        }
                    }
                }
            }
        }
    }
}

Can you please tell me - what I am doing wrong to fetch required information.

**Comment by devops-arena** [comment]
Try this
def triggerCause = currentBuild.rawBuild.getCause(com.adobe.jenkins.github_pr_comment_build.GitHubPullRequestCommentCause)
echo("Build was started by ${triggerCause.commentBody}")

**Comment by om3171991** [comment]
@devops-arena - Getting below error message -

Scripts not permitted to use method com.adobe.jenkins.github_pr_comment_build.GitHubPullRequestCommentCause getCommentBody. Administrators can decide whether to approve or reject this signature.

**Comment by devops-arena** [comment]
@om3171991 You need to go to Manage Jenkins --> In-process Script Approval --> Approve the signature

**Comment by om3171991** [comment]
@devops-arena - any other way around, don't have access to enable this. Our Jenkins is managed by the central team and it's a little tough to get this enabled.

**Comment by bluesliverx** [comment]
I have pushed a fix for this, at least it has worked in other plugins. As soon as it builds correctly and gets merged, I'll do a new release.

**Comment by om3171991** [comment]
@bluesliverx - Thanks. Much appreciated. Do we need to reconfigure the plugin to get this change under our Jenkins server?

**Comment by bluesliverx** [comment]
You would need to upgrade the plugin once it is released. This may take a few hours (up to a day) to the newest version in the repositories. Unfortunately, they have changed the release process since the last time I did this, and now I need to wait for https://github.com/jenkins-infra/repository-permissions-updater/pull/2090 to be merged before I can release.

**Comment by bluesliverx** [comment]
I changed the versioning scheme for incremental releases, and 58.v945be9f1661f has been released with the fix for this.

**Comment by bluesliverx** [comment]
Looking at `currentBuild.getBuildCauses()` (or its override), I do not see the body/author/URL attributes included in the generated JSON. This is likely because of #37. I'll release this and check it later to see if that fixes the issue.

**Comment by bluesliverx** [comment]
I won't be able to upgrade our server until later tonight, so if anyone gets a chance to try out the latest release (`61.v...`) and see if it works, let me know.

**Comment by bluesliverx** [comment]
Success! This build works great. Here is what I included in my Jenkinsfile:

```
echo("build causes: ${currentBuild.getBuildCauses()}")
```

Here is the output:

```
build causes: [[_class:com.adobe.jenkins.github_pr_comment_build.GitHubPullRequestCommentCause, shortDescription:GitHub pull request comment, commentAuthor:saville, commentBody:this is comment, commentUrl:https://github.com/jenkinsci/github-pr-comment-build/pull/1#issuecomment-1234]]
```
