### ISSUE TITLE
Unable to trigger build with wildcard in the comment body 

### ISSUE THREAD

**Issue by ManjuAsthuthe** [jenkinsci/github-pr-comment-build-plugin#38]
<img width="865" alt="wildcardNotWorking" src="https://user-images.githubusercontent.com/38680802/136166659-36dc74b1-7299-4c07-a248-8217a906729a.png">
Build is not getting trigerred if wildcard is mentioned in the comment body 
for ex - if the comment body is ^buildzip*$ and on mentioning "buildzip test env" in the PR comment won't trigger the build 
however if the comment body is ^buildzip$ and on mentioning "buildzip" in the PR comment will trigger the build 

On removing wild card(*) build is getting trigerred and on having wildcard in the comment body build is not getting trigerred 
Please help me with this issue

**Comment by bluesliverx** [comment]
Yup, it's a regular expression. Glad you got it sorted.
