### ISSUE TITLE
Restrict build trigger to project group members

### ISSUE THREAD

**Issue by lprimak** [jenkinsci/github-pr-comment-build-plugin#42]
### What feature do you want to see added?

I would like only the project members to be able to trigger builds.
However, there is no way to do this with the plugin.
Anyone can make a fork / PR to the project and kick off a build with a PR comment.
Is there any way to restrict this to project members?

Thanks!

**Comment by lprimak** [comment]
Any chance this gets escalated a bit? Thanks!

**Comment by bluesliverx** [comment]
Hmm, how would you suggest this is done? I haven't been in this area for a long time and I'm fuzzy on what the configuration even looks like at the moment.

**Comment by lprimak** [comment]
Something similar to this in the https://plugins.jenkins.io/basic-branch-build-strategies plugin:
Docs here: https://github.com/jenkinsci/basic-branch-build-strategies-plugin/blob/master/docs/user.adoc

![image](https://user-images.githubusercontent.com/1002484/173454306-38978c3a-134f-4fce-a322-1339abb92c42.png)

**Comment by lprimak** [comment]
Or, better yet, this:
https://github.com/jenkinsci/pipeline-github-plugin#issuecommenttrigger

**Comment by lprimak** [comment]
In progress

**Comment by lprimak** [comment]
Well tested and ready to go!

**Comment by snorlaX-sleeps** [comment]
We are using this plugin because https://github.com/jenkinsci/pipeline-github-plugin#issuecommenttrigger doesn't support Github teams as collaborators, only individually added users (which blocks operating at scale)

Can you ensure the change supports teams and individual users, similar to https://github.com/jenkinsci/pipeline-github-plugin/pull/111/files#diff-f28baadffa29cdf918bc3cf814038606eb0abab1e61dfe9e380b50aafe020d74R39 (which may take a long time to release), or that the new functionality can be disabled please?

**Comment by lprimak** [comment]
Right now this change doesn’t support teams however this is a good suggestion I’ll implement it. 
the functionality can be turned off currently as well

**Comment by lprimak** [comment]
@snorlaX-sleeps testing this change now... should be good in an hour :)

**Comment by lprimak** [comment]
it's done...simple stuff

**Comment by lprimak** [comment]
@bluesliverx please review... thank you!

**Comment by snorlaX-sleeps** [comment]
@lprimak thanks for implementing the change, means I can keep using the plugin :)

**Comment by aRobinson-R7** [comment]
@lprimak change looks good, able to disable the new functionality.
Couldn't figure out why my PR's weren't triggering this morning xD

**Comment by snorlaX-sleeps** [comment]
@lprimak change looks good, able to disable the new functionality.
Couldn't figure out why my PR's weren't triggering this morning xD
