### ISSUE TITLE
Trigger more than one job with single PR comment

### ISSUE THREAD

**Issue by Tallaban** [jenkinsci/github-pr-comment-build-plugin#49]
### Jenkins and plugins versions report

Hello,
I would like to ask a question if your plugin parses further jobs to run if it finds a match? I have a case where I have two separate jobs which I want to trigger with the same PR comment, but logs show it runs only the first match and does not analyze the rest of them. Is this behavior created by design or this is a bug? I am using Jenkins in ver. 2.332.1, GitHub enterprise server 3.3.7 and GitHub PR Comment Build Version: 78.v2dcf62ba199b.

### What Operating System are you using (both controller, and any agents involved in the problem)?

RHEL 8.5 (Ootpa)

### Reproduction steps

1. Step: Clone job which you can trigger by PR comment (i.e. run forest).
2. Step: Try to trigger those jobs by comment.

### Expected Results

Run n-jobs triggered by the same comment

### Actual Results

Run first match

**Comment by lprimak** [comment]
There is a bit of history behind this, see #27 and #32 
Bottom line is that there is a PR with a fix, but hasn't been merged yet: #48
