### ISSUE TITLE
Triggerring more than one job with single PR comment is broken

### ISSUE THREAD

**Issue by gvreddy579** [jenkinsci/github-pr-comment-build-plugin#55]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Jenkins: [CloudBees CI Managed Controller 2.346.2.3-rolling](https://release-notes.cloudbees.com/product/141)
  github-pr-comment-build version: 78.v2dcf62ba199b
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux, Agents are all Kubernetes agents

### Reproduction steps

- Install `61.v49f749d31d98` version of plugin
- Create multiple Jenkins files in the same repo
- Create multiple branch jobs for all the jenkinsfiles created in the same repo
- Configure all the jobs to be configured to be triggered from a PR comment
- Create a PR and comment on the PR, All the jobs are triggered.
- Now upgrade the plugin to new version: `78.v2dcf62ba199b`
- Comment again on the same PR, one a single job is triggerred.

### Expected Results

The plugin is expected to be working as before, triggering all the jobs that are matching the criteria of jobs that are configured to be kicked of for a PR comment

### Actual Results

Triggering only the first job from the list of jobs configured to run on a single PR comment

### Anything else?

This is working as expected in the older version: `61.v49f749d31d98`
After we have upgraded to the new version: `78.v2dcf62ba199b`  this functionality seems to be broken

I suspect, this is broken because of https://github.com/jenkinsci/github-pr-comment-build-plugin/pull/48

**Comment by lprimak** [comment]
How are you.creating multiple Jenkins files I. The same repo?  This seems to be a very esoteric use case and probably is not supported

**Comment by gvreddy579** [comment]
@lprimak This is a very common case, where there are multiple Jenkins files in a single repo.

**Comment by lprimak** [comment]
Sorry @gvreddy579 never mind my old comment. 
There is the newest version (86.v23ae6d00ab99) that fixes this issue.
The version you are trying to run was pre-#48

**Comment by lprimak** [comment]
duplicate of #49

**Comment by lprimak** [comment]
@bluesliverx can you please close this issue?
Thanks

**Comment by gvreddy579** [comment]
Solved in https://github.com/jenkinsci/github-pr-comment-build-plugin/issues/49
