### ISSUE TITLE
Document the requirement for branch discovery behavior

### ISSUE THREAD

**Issue by ncreep** [jenkinsci/github-pr-comment-build-plugin#58]
### Describe your use-case which is not covered by existing documentation.

Hi,

As I was trying to set up the PR comment plugin on my Jenkins setup, I stumbled on the fact that (somewhat related to #20) I didn't get any triggers because I didn't use a "Discover pull request ..." behavior for my project. Instead I was using "Discover branches".

Since it seemed non-obvious to me that there was a hard requirement on the discovery behavior, I think it would be worthwhile to document this in the README file, and maybe add some more logs in that area.

Will you be open to a pull request documenting/logging this fact?

Thanks

**Comment by lppedd** [comment]
Can I ask you why you're not discovering PRs?

**Comment by bluesliverx** [comment]
Absolutely, would very much welcome PRs for documentation.

**Comment by bluesliverx** [comment]
@ncreep thanks for the PR! Got it merged.
