### ISSUE TITLE
For private repositories people with Read role can trigger builds

### ISSUE THREAD

**Issue by pascal-hofmann** [jenkinsci/github-pr-comment-build-plugin#61]
For private repositories people with `Read` role (aka pull permission) are seen as collaborators by the GitHub API. This means, they are able to trigger builds.

In addition it would be great if there was a way to only trust users with admin permission. This way people with push permission could still collaborate on the same branches of a repo, but sensitive builds could only be triggered by authorized people.

**Comment by lprimak** [comment]
This issue can be closed.
