### ISSUE TITLE
Can we add environment variables to a triggered job?

### ISSUE THREAD

**Issue by haos616** [jenkinsci/github-pr-comment-build-plugin#8]
Example: `ghprbTriggerAuthorLogin` in ghprb plugin.

**Comment by bluesliverx** [comment]
I believe you can get this information already by getting the build causes in a pipeline script. However, it would need to be an approved script by the Jenkins admin.  I don't have the time to add it to this plugin currently, but I would welcome any pull requests made against the repository if you want to tackle it yourself.
