### ISSUE TITLE
GitHub Pull Request Comment Build Plugin configuration doesn't appear in Jenkins->Configure System page

### ISSUE THREAD

**Issue by zavale** [jenkinsci/github-pr-comment-build-plugin#9]
I installed the plugin, restarted Jenkins, however, the configuration of GitHub Pull Request Comment Build Plugin doesn't show up in Configure page

**Comment by bluesliverx** [comment]
Where exactly are you looking for this on the configure page? Are you attempting to add a branch property to the multibranch pipeline job?

**Comment by zavale** [comment]
@bluesliverx 
Manage Jenkins -> Configure System
Configuration for  `GitHub Pull Request Comment Build Plugin`  doesn't appear there
The plugin itself is installed

**Comment by bluesliverx** [comment]
@zavale I'm not sure why you're checking there to be honest.  This is configured on individual multibranch pipeline jobs, not on the system in general.  In other words, you must add the branch property to each job, it is not globally configured.

**Comment by zavale** [comment]
@bluesliverx Thanks, you are right - it's just was not obvious. Closing the issue

**Comment by bluesliverx** [comment]
@tylersmith34, took me awhile to get back to this, but I agree. I added some more docs today to hopefully make it clearer.
